[package]
name = "semantic_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
kigiri_memory = { path = "../kigiri_memory" }
parser = { path = "../parser" }
thiserror = { workspace = true }
bumpalo = { workspace = true }