[workspace]
members = ["parser", "type_engine", "codegen"]
resolver = "3"

[workspace.dependencies]
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
pest = "2.8.0"
pest_derive = "2.8.0"
string-interner = "0.19.0"
bumpalo = "3.17.0"
thiserror = "2.0.12"
