[workspace]
members = ["codegen", "parser"]
resolver = "3"

[workspace.dependencies]
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
pest = "2.8.0"
pest_derive = "2.8.0"
string-interner = "0.19.0"
bumpalo = "3.17.0"
