[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = { path = "../parser" }
semantic_analysis = { path = "../semantic_analysis" }
bumpalo = { workspace = true, features = ["collections"] }
