[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = { path = "../parser" }
type_engine = { path = "../semantic_analysis" }
bumpalo = { workspace = true, features = ["collections"] }
