[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
kigiri_memory = { path = "../kigiri_memory" }
pest = { workspace = true }
pest_derive = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
