[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
string-interner = { workspace = true }
bumpalo = { workspace = true }
